modLoader = "javafml"
loaderVersion = "[2,)"
logoFile = "logo.png"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "todo_list"
version = "${version}"
displayName = "Todo List"
authors = "ENC_Euphony"
description = '''
A simple to-do list system that is highly integrated with Minecraft
'''
#logoFile = ""

[[dependencies.todo_list]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.todo_list]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "todo_list.mixins.json"
